export const ALL_STORIES_REQUEST = "ALL_STORIES_REQUEST";
export const ALL_STORIES_SUCCESS = "ALL_STORIES_SUCCESS";
export const ALL_STORIES_FAIL = "ALL_STORIES_FAIL";

export const STORY_DETAILS_SUCCESS = "STORY_DETAILS_SUCCESS";
export const STORY_DETAILS_REQUEST = "STORY_DETAILS_REQUEST";
export const STORY_DETAILS_FAIL = "STORY_DETAILS_FAIL";

export const STORY_GENERATE_SUCCESS = "STORY_DETAILS_SUCCESS";
export const STORY_GENERATE_REQUEST = "STORY_DETAILS_REQUEST";
export const STORY_GENERATE_FAIL = "STORY_DETAILS_FAIL";

export const STORY_AUDIO_SUCCESS = "STORY_AUDIO_SUCCESS";
export const STORY_AUDIO_REQUEST = "STORY_AUDIO_REQUEST";
export const STORY_AUDIO_FAIL = "STORY_AUDIO_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
