//get all
export const ALL_STORIES_REQUEST = "ALL_STORIES_REQUEST";
export const ALL_STORIES_SUCCESS = "ALL_STORIES_SUCCESS";
export const ALL_STORIES_FAIL = "ALL_STORIES_FAIL";

//get story by id
export const STORY_DETAILS_SUCCESS = "STORY_DETAILS_SUCCESS";
export const STORY_DETAILS_REQUEST = "STORY_DETAILS_REQUEST";
export const STORY_DETAILS_FAIL = "STORY_DETAILS_FAIL";

//post new story
export const STORY_GENERATE_SUCCESS = "STORY_DETAILS_SUCCESS";
export const STORY_GENERATE_REQUEST = "STORY_DETAILS_REQUEST";
export const STORY_GENERATE_FAIL = "STORY_DETAILS_FAIL";

//get story audio by id
export const STORY_AUDIO_SUCCESS = "STORY_AUDIO_SUCCESS";
export const STORY_AUDIO_REQUEST = "STORY_AUDIO_REQUEST";
export const STORY_AUDIO_FAIL = "STORY_AUDIO_FAIL";

//followup question
export const FOLLOWUP_QUESTION_SUCCESS = "FOLLOWUP_QUESTION_SUCCESS";
export const FOLLOWUP_QUESTION_REQUEST = "FOLLOWUP_QUESTION_REQUEST";
export const FOLLOWUP_QUESTION_FAIL = "FOLLOWUP_QUESTION_FAIL";

//clear errors
export const CLEAR_ERRORS = "CLEAR_ERRORS";
